title: 0xtraderL Blog
lang: en
url: "https://0xtraderl.github.io"
description: >-
  A blog powered by Jekyll and Chirpy.
author:
  name: 0xtraderL
  bio: Geek, trader, and blogger.
  email: your-email@example.com

# Theme
theme: jekyll-theme-chirpy

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog

# Social links (optional, can be filled later)
social:
  github: 0xtraderL

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 