title: 0xtraderL Blog
email: your-email@example.com
description: >- # this means to ignore newlines until 
  A blog powered by Jekyll and GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0xtraderl.github.io" # the base hostname & protocol for your site

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor 