title: 0xtraderL Blog
lang: en
url: "https://0xtraderl.github.io"
description: >-
  A blog powered by Jekyll and Chirpy.
author:
  name: 0xtraderL
  bio: Geek, trader, and blogger.
  email: your-email@example.com

# Theme
theme: jekyll-theme-chirpy

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
timezone: Asia/Shanghai

# Social links (optional, can be filled later)
social:
  github: 0xtraderL

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-archives
  - jekyll-include-cache

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /:categories/:year/:month/:day/:title/
  - scope:
      path: "_tabs"
      type: tabs
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: "assets/img/favicons"
    values:
      swcache: true
  - scope:
      path: "assets/js/dist"
    values:
      swcache: true

# Exclude from processing
exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - package*.json
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock 