title: traderL
lang: zh-CN
url: "https://0xtraderl.github.io"
description: >-
  A blog powered by Jekyll and Chirpy.
author:
  name: traderL
  bio: Geek, trader, and blogger.
  email: your-email@example.com

# Theme
theme: jekyll-theme-chirpy

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
timezone: Asia/Shanghai

# Social links (optional, can be filled later)
social:
  github: ""

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /:categories/:year/:month/:day/:title/
  - scope:
      path: "_tabs"
      type: tabs
    values:
      layout: page
      permalink: /:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - package*.json 